---
kind: pipeline
type: kubernetes
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git fetch --tags
  - git submodule update --init --recursive

- name: docker
  image: harbor.ntppool.org/ntppool/drone-kaniko:main
  pull: always
  settings:
    repo: ntppool/ntppool
    registry: harbor.ntppool.org
    tags: SHAABBREV,SHA7,${DRONE_BRANCH}
    auto_tag: true
    cache: true
    username:
      from_secret: harbor_username
    password:
      from_secret: harbor_password
---
kind: signature
hmac: a0bb8189d87668bb32165e34e1d660947effabf3696facf169826e590ea963fe

...
